server:
  port: 4006

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-routes
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patient, /api/patient/**
          filters:
            - StripPrefix=1

        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs