server:
  port: 4006

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-routes
          uri: http://auth-service:4007
          predicates:
            - Path=/auth/*
          filters:
            - StripPrefix=1


        - id: patient-service-routes
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patient, /api/patient/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4007
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs